name: Build Plugin
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cobigen-plugin
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: npm install
      
      - name: install vs code extensions package
        run: sudo npm install -g vsce

      - name: build vsix file
        run: vsce package

      - name: create artifact
        uses: actions/upload-artifact@v2
        with: 
          name: cobigen-plugin.vsix
          path: ./*vsix
